=== nkvoronov/arch_media/multimedia/tv/vdr/plugins/vdr-skindesigner/vdr-skindesigner/pkg/vdr-skindesigner/usr/share/vdr/plugins/skindesigner/dtd/globals.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT globals (colors | variables | translations | fonts)*>
<!ELEMENT colors (color)*>
<!ELEMENT variables (var)*>
<!ELEMENT translations (token)*>
<!ELEMENT fonts (font)*>

<!ELEMENT color (#PCDATA)>
<!ATTLIST color
  name NMTOKEN #REQUIRED>

<!ELEMENT var (#PCDATA)>
<!ATTLIST var
  name NMTOKEN #REQUIRED
  type (int|double|string) #REQUIRED>

<!ELEMENT token (trans)+>
<!ATTLIST token
  name CDATA #REQUIRED>

<!ELEMENT trans (#PCDATA)>
<!ATTLIST trans
  lang NMTOKEN #REQUIRED>

<!ELEMENT font (#PCDATA)>
<!ATTLIST font
  name NMTOKEN #REQUIRED>

=== nkvoronov/arch_media/multimedia/tv/vdr/plugins/vdr-skindesigner/vdr-skindesigner/pkg/vdr-skindesigner/usr/share/vdr/plugins/skindesigner/skins/metrixhd/themes/complementary/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE globals SYSTEM "../../../../dtd/globals.dtd">

<globals>
    <colors>
        <color name="menuback">DDC7B097</color>
        <color name="menualternate">33FFFFFF</color>
        <color name="menuheader">DD98AFC7</color>
        <color name="menuactive">DD98AFC7</color>
        <color name="menuseparator">33FFFFFF</color>
        <color name="fontactive">FF333333</color>
        <color name="fontmenuactive">FF333333</color>
        <color name="fontdefault">FF555555</color>
        <color name="fontseparator">FF000000</color>
        <color name="scrollbar">FF666666</color>
        <!-- colors svg templates -->
        <color name="icon">FF666666</color>
        <color name="iconactive">FF333333</color>
        <color name="iconselected">FF000000</color>
        <color name="iconrecactive">EFFFFFFF</color>
        <color name="iconrecinactive">FF000000</color>
        <color name="icontextalert">FFFF5050</color>
    </colors>

    <variables>
    </variables>

    <translations>
    </translations>

    <fonts>
        <font name="light">VDROpen Sans:Regular</font>
    </fonts>
</globals>

=== nkvoronov/arch_media/multimedia/tv/vdr/plugins/vdr-skindesigner/vdr-skindesigner/pkg/vdr-skindesigner/usr/share/vdr/plugins/skindesigner/skins/estuary4vdr/themes/darkred/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE globals SYSTEM "../../../../dtd/globals.dtd">

<globals>
    <!--
    define all your needed colors here
    -->
    <colors>
        <color name="menuback">55000000</color>
        <color name="menubackline">FF444444</color>
        <color name="menubackactive">FF550000</color>
        <color name="menubackactivedark">FF330000</color>
        <color name="menumainheader">FF000000</color>
        <color name="channelback">B0000000</color>
        <color name="messageback">D0000000</color>
        <color name="replayback">B0000000</color>
        <color name="fontdefault">FFCCCCCC</color>
        <color name="fontactive">FF770000</color>
        <color name="fontmenuactive">FFFFFFFF</color>
        <color name="progressbarback">FF222222</color>
        <color name="progressbar">FF550000</color>
        <color name="progressbartimeshift">FF666666</color>
        <color name="cutmark">FF666666</color>
        <color name="icontextactive">FFFFFFFF</color>
        <color name="icontextinactive">FFCCCCCC</color>
        <color name="icontextalert">FFFF0000</color>
        <!-- colors svg templates -->
        <color name="icon">FFCCCCCC</color>
        <color name="iconactive">FFFFFFFF</color>
        <color name="iconselected">FF800000</color>
        <color name="iconrecactive">FF550000</color>
        <color name="iconrecinactive">FFFFFFFF</color>
        <!-- colors tvguideng -->
        <color name="tvgrecmenuback">FF000000</color>
        <color name="tvgbuttoninactive">FF666666</color>
        <color name="tvgtimeline">FFAA0000</color>
        <color name="tvgtextedit">FF111111</color>
        <color name="tvgtextedittext">FFFFFFFF</color>
        <color name="tvgtextnotedit">FFFFFFFF</color>
        <color name="tvgtextnotedittext">FF333333</color>
        <color name="tvgdayactive">FF52A300</color>
        <color name="tvgdayinactive">FFA30000</color>
        <color name="tvgdayselected">AA000000</color>
        <color name="tvgconflictheaderback">FF444444</color>
        <color name="tvgconflictfont">FFAA0000</color>
        <color name="tvgconflict">88AA0000</color>
        <color name="tvgconflicttimer">FF000000</color>
        <color name="tvgtimeline1">FF000000</color>
        <color name="tvgtimeline2">FFFFFFFF</color>
    </colors>
    <!--
    these variables can be used everywhere in the templates
    variabls of type int can also be used as conditions, just
    set such a variable to 1 for true and 0 for false
    -->
    <variables>
    </variables>
    <!--
    translations used in the skin
    -->
    <translations>
    </translations>
    <!--
    The three Fonts FontOSD, FontFix and FontSml configured in VDR
    can be used in all template "font" attributes with this tokens:
    {vdrOsd}
    {vdrFix}
    {vdrSml} 
    If you like to use further fonts, just define them below.
    Syntax:
    <font name="tokenname">fontname</font>
    These fonts can then also be used in all templates in the "font" 
    attribute.
    if an invalid font is used in a template, vdrOsd is used as default.
    -->
    <fonts>
    </fonts>
</globals>

=== nkvoronov/arch_media/multimedia/tv/vdr/plugins/vdr-skindesigner/vdr-skindesigner/pkg/vdr-skindesigner/usr/share/vdr/plugins/skindesigner/skins/metrixhd/themes/raspberry/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE globals SYSTEM "../../../../dtd/globals.dtd">

<globals>
    <colors>
        <color name="menuback">EE8CC04B</color>
<!--        <color name="menualternate">EE75a968</color> -->
        <color name="menuheader">EEC7053D</color>
        <color name="menuactive">EFC7053D</color>
        <color name="menuseparator">33FFFFFF</color>
        <color name="fontdefault">FF000000</color>
        <color name="fontseparator">FF000000</color>
        <!-- colors svg templates -->
        <color name="icon">FF000000</color>
        <color name="iconactive">FFFFFFFF</color>
        <color name="iconselected">FF000000</color>
        <color name="iconrecactive">EFFFFFFF</color>
        <color name="iconrecinactive">FF000000</color>
    </colors>

    <variables>
    </variables>

    <translations>
    </translations>

    <fonts>
        <font name="light">VDROpen Sans:Regular</font>
    </fonts>
</globals>

=== nkvoronov/arch_media/multimedia/tv/vdr/plugins/vdr-skindesigner/vdr-skindesigner/pkg/vdr-skindesigner/usr/share/vdr/plugins/skindesigner/skins/metrixhd/themes/birdie/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE globals SYSTEM "../../../../dtd/globals.dtd">

<globals>
    <colors>
        <color name="menuback">C0FFA500</color>
        <color name="menuheader">C0111111</color>
        <color name="menuactive">F0111111</color>
<!--        <color name="menualternate">C0F5B914</color> -->
        <color name="menuseparator">22FFFFFF</color>
        <color name="fontdefault">F0111111</color>
        <color name="fontseparator">F0111111</color>
        <color name="scrollbar">F0111111</color>
        <!-- colors svg templates -->
        <color name="iconactive">FFFFFFFF</color>
        <color name="icon">F0111111</color>
        <color name="iconselected">FF800000</color>
        <color name="iconrecactive">F0FFFFFF</color>
        <color name="iconrecinactive">F0111111</color>
    </colors>

    <variables>
    </variables>

    <translations>
    </translations>

    <fonts>
    </fonts>
</globals>
